### ISSUE TITLE
Get an uncaught error when try to remove event listeners

### ISSUE THREAD

**Issue by elverskog** [cmswalker/scroll-swipe#2]
I get this error below. 

`ScrollSwipe.js:96 Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.`

Your module is used in fullpage-react, which is where I am having my issues but by the error it looks like the it may fail elsewhere. Maybe it depends on how it is built/deployed?

As a test I started to going through and moving the inline functions (like `this.target.addEventListener('wheel', <inline function>)`)  into their own functions off ScrollSwipe.prototype. This way I could add said function as the second arg in the removeEventListener call. Like `this.target.removeEventListener('wheel', this.preventWheelDefault);`

This is working so far but I got a few to get through before it stops breaking my call that is trying to unload these bindings.

Hopefully this isn't a red herring. Let me know if you need anything else. Thanks for the module!

**Comment by cmswalker** [comment]
@elverskog I own both this and fullpage-react, could you show me the code you are using for fullpage-react?  I assume you are not interacting with scrollSwipe directly right?

**Comment by elverskog** [comment]
Of course. Thanks. It's pretty much right out of the demo (same nextSlide functions etc). Let me know if you need more (I can send github link or something). My app however is not a pure one page app. The error I get is when I try to link to another path (via react router 4). I have to click said link twice to get to the other page. The URL changes on the first click but the page only re-renders on the second click . A assume the first attempt at re-render is blocked by the error I described above. 

```
import { Fullpage, Slide, HorizontalSlider, Overlay, changeHorizontalSlide, changeFullpageSlide } from 'fullpage-react'

      <div>
        <Fullpage onSlideChangeStart={this.onSlideChangeStart} onSlideChangeEnd={this.onSlideChangeEnd} {...fullPageOptions}>
          <HeaderBar {...props} />
          <Slide>
            <HomeIntro {...props} />
          </Slide>
          <Slide>
            <HomeHow {...props} />
          </Slide>
          <Slide>
            <HomeWhat {...props} />
          </Slide>
        </Fullpage>
        <Helmet title='Home' />
      </div>
```

**Comment by cmswalker** [comment]
@elverskog this has now been fixed both here and as a dependency in v3 of fullpage-react.
